name: Deploy to  EC2

on:
  push:
    branches:
      - main

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh 
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/ec2_key.pem 
          chmod 600 ~/.ssh/ec2_key.pem 

      - name: Copy source code to EC2
        run: |
          rsync -avz \
          -e "ssh -i ~/.ssh/ec2_key.pem -p 22 -o StrictHostKeyChecking=no" \
          ./ \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/app


      - name: Run deploy script on EC2
        run: |
          EC2_USER=${{ secrets.EC2_USER }}
          EC2_HOST=${{ secrets.EC2_HOST }}
          ssh -i ~/.ssh/ec2_key.pem -p 22 -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
          cd /home/$EC2_USER/app
          chmod +x deploy.sh
          ./deploy.sh
          EOF